// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.gossip.protobuf;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface hearGossipRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hearGossipRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string msg = 1;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 1;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>optional .Clock clk = 2;</code>
     *
     * <pre>
     * You have to define the protobuf
     * </pre>
     */
    boolean hasClk();
    /**
     * <code>optional .Clock clk = 2;</code>
     *
     * <pre>
     * You have to define the protobuf
     * </pre>
     */
    com.gossip.protobuf.MessageProtos.Clock getClk();
    /**
     * <code>optional .Clock clk = 2;</code>
     *
     * <pre>
     * You have to define the protobuf
     * </pre>
     */
    com.gossip.protobuf.MessageProtos.ClockOrBuilder getClkOrBuilder();
  }
  /**
   * Protobuf type {@code hearGossipRequest}
   */
  public static final class hearGossipRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hearGossipRequest)
      hearGossipRequestOrBuilder {
    // Use hearGossipRequest.newBuilder() to construct.
    private hearGossipRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private hearGossipRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final hearGossipRequest defaultInstance;
    public static hearGossipRequest getDefaultInstance() {
      return defaultInstance;
    }

    public hearGossipRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private hearGossipRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              msg_ = bs;
              break;
            }
            case 18: {
              com.gossip.protobuf.MessageProtos.Clock.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = clk_.toBuilder();
              }
              clk_ = input.readMessage(com.gossip.protobuf.MessageProtos.Clock.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(clk_);
                clk_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gossip.protobuf.MessageProtos.internal_static_hearGossipRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gossip.protobuf.MessageProtos.internal_static_hearGossipRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gossip.protobuf.MessageProtos.hearGossipRequest.class, com.gossip.protobuf.MessageProtos.hearGossipRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<hearGossipRequest> PARSER =
        new com.google.protobuf.AbstractParser<hearGossipRequest>() {
      public hearGossipRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new hearGossipRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<hearGossipRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MSG_FIELD_NUMBER = 1;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 1;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string msg = 1;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLK_FIELD_NUMBER = 2;
    private com.gossip.protobuf.MessageProtos.Clock clk_;
    /**
     * <code>optional .Clock clk = 2;</code>
     *
     * <pre>
     * You have to define the protobuf
     * </pre>
     */
    public boolean hasClk() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Clock clk = 2;</code>
     *
     * <pre>
     * You have to define the protobuf
     * </pre>
     */
    public com.gossip.protobuf.MessageProtos.Clock getClk() {
      return clk_;
    }
    /**
     * <code>optional .Clock clk = 2;</code>
     *
     * <pre>
     * You have to define the protobuf
     * </pre>
     */
    public com.gossip.protobuf.MessageProtos.ClockOrBuilder getClkOrBuilder() {
      return clk_;
    }

    private void initFields() {
      msg_ = "";
      clk_ = com.gossip.protobuf.MessageProtos.Clock.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, clk_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, clk_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gossip.protobuf.MessageProtos.hearGossipRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gossip.protobuf.MessageProtos.hearGossipRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gossip.protobuf.MessageProtos.hearGossipRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gossip.protobuf.MessageProtos.hearGossipRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gossip.protobuf.MessageProtos.hearGossipRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gossip.protobuf.MessageProtos.hearGossipRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gossip.protobuf.MessageProtos.hearGossipRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gossip.protobuf.MessageProtos.hearGossipRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gossip.protobuf.MessageProtos.hearGossipRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gossip.protobuf.MessageProtos.hearGossipRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gossip.protobuf.MessageProtos.hearGossipRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hearGossipRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hearGossipRequest)
        com.gossip.protobuf.MessageProtos.hearGossipRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gossip.protobuf.MessageProtos.internal_static_hearGossipRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gossip.protobuf.MessageProtos.internal_static_hearGossipRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gossip.protobuf.MessageProtos.hearGossipRequest.class, com.gossip.protobuf.MessageProtos.hearGossipRequest.Builder.class);
      }

      // Construct using com.gossip.protobuf.MessageProtos.hearGossipRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getClkFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (clkBuilder_ == null) {
          clk_ = com.gossip.protobuf.MessageProtos.Clock.getDefaultInstance();
        } else {
          clkBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gossip.protobuf.MessageProtos.internal_static_hearGossipRequest_descriptor;
      }

      public com.gossip.protobuf.MessageProtos.hearGossipRequest getDefaultInstanceForType() {
        return com.gossip.protobuf.MessageProtos.hearGossipRequest.getDefaultInstance();
      }

      public com.gossip.protobuf.MessageProtos.hearGossipRequest build() {
        com.gossip.protobuf.MessageProtos.hearGossipRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gossip.protobuf.MessageProtos.hearGossipRequest buildPartial() {
        com.gossip.protobuf.MessageProtos.hearGossipRequest result = new com.gossip.protobuf.MessageProtos.hearGossipRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (clkBuilder_ == null) {
          result.clk_ = clk_;
        } else {
          result.clk_ = clkBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gossip.protobuf.MessageProtos.hearGossipRequest) {
          return mergeFrom((com.gossip.protobuf.MessageProtos.hearGossipRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gossip.protobuf.MessageProtos.hearGossipRequest other) {
        if (other == com.gossip.protobuf.MessageProtos.hearGossipRequest.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          bitField0_ |= 0x00000001;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasClk()) {
          mergeClk(other.getClk());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gossip.protobuf.MessageProtos.hearGossipRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gossip.protobuf.MessageProtos.hearGossipRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 1;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }

      private com.gossip.protobuf.MessageProtos.Clock clk_ = com.gossip.protobuf.MessageProtos.Clock.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.gossip.protobuf.MessageProtos.Clock, com.gossip.protobuf.MessageProtos.Clock.Builder, com.gossip.protobuf.MessageProtos.ClockOrBuilder> clkBuilder_;
      /**
       * <code>optional .Clock clk = 2;</code>
       *
       * <pre>
       * You have to define the protobuf
       * </pre>
       */
      public boolean hasClk() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Clock clk = 2;</code>
       *
       * <pre>
       * You have to define the protobuf
       * </pre>
       */
      public com.gossip.protobuf.MessageProtos.Clock getClk() {
        if (clkBuilder_ == null) {
          return clk_;
        } else {
          return clkBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Clock clk = 2;</code>
       *
       * <pre>
       * You have to define the protobuf
       * </pre>
       */
      public Builder setClk(com.gossip.protobuf.MessageProtos.Clock value) {
        if (clkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clk_ = value;
          onChanged();
        } else {
          clkBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Clock clk = 2;</code>
       *
       * <pre>
       * You have to define the protobuf
       * </pre>
       */
      public Builder setClk(
          com.gossip.protobuf.MessageProtos.Clock.Builder builderForValue) {
        if (clkBuilder_ == null) {
          clk_ = builderForValue.build();
          onChanged();
        } else {
          clkBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Clock clk = 2;</code>
       *
       * <pre>
       * You have to define the protobuf
       * </pre>
       */
      public Builder mergeClk(com.gossip.protobuf.MessageProtos.Clock value) {
        if (clkBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              clk_ != com.gossip.protobuf.MessageProtos.Clock.getDefaultInstance()) {
            clk_ =
              com.gossip.protobuf.MessageProtos.Clock.newBuilder(clk_).mergeFrom(value).buildPartial();
          } else {
            clk_ = value;
          }
          onChanged();
        } else {
          clkBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Clock clk = 2;</code>
       *
       * <pre>
       * You have to define the protobuf
       * </pre>
       */
      public Builder clearClk() {
        if (clkBuilder_ == null) {
          clk_ = com.gossip.protobuf.MessageProtos.Clock.getDefaultInstance();
          onChanged();
        } else {
          clkBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Clock clk = 2;</code>
       *
       * <pre>
       * You have to define the protobuf
       * </pre>
       */
      public com.gossip.protobuf.MessageProtos.Clock.Builder getClkBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getClkFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Clock clk = 2;</code>
       *
       * <pre>
       * You have to define the protobuf
       * </pre>
       */
      public com.gossip.protobuf.MessageProtos.ClockOrBuilder getClkOrBuilder() {
        if (clkBuilder_ != null) {
          return clkBuilder_.getMessageOrBuilder();
        } else {
          return clk_;
        }
      }
      /**
       * <code>optional .Clock clk = 2;</code>
       *
       * <pre>
       * You have to define the protobuf
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.gossip.protobuf.MessageProtos.Clock, com.gossip.protobuf.MessageProtos.Clock.Builder, com.gossip.protobuf.MessageProtos.ClockOrBuilder> 
          getClkFieldBuilder() {
        if (clkBuilder_ == null) {
          clkBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.gossip.protobuf.MessageProtos.Clock, com.gossip.protobuf.MessageProtos.Clock.Builder, com.gossip.protobuf.MessageProtos.ClockOrBuilder>(
                  getClk(),
                  getParentForChildren(),
                  isClean());
          clk_ = null;
        }
        return clkBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:hearGossipRequest)
    }

    static {
      defaultInstance = new hearGossipRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hearGossipRequest)
  }

  public interface ClockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Clock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 Process = 1;</code>
     */
    boolean hasProcess();
    /**
     * <code>optional int32 Process = 1;</code>
     */
    int getProcess();

    /**
     * <code>optional int32 Count = 2;</code>
     */
    boolean hasCount();
    /**
     * <code>optional int32 Count = 2;</code>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code Clock}
   */
  public static final class Clock extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Clock)
      ClockOrBuilder {
    // Use Clock.newBuilder() to construct.
    private Clock(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Clock(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Clock defaultInstance;
    public static Clock getDefaultInstance() {
      return defaultInstance;
    }

    public Clock getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Clock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              process_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gossip.protobuf.MessageProtos.internal_static_Clock_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gossip.protobuf.MessageProtos.internal_static_Clock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gossip.protobuf.MessageProtos.Clock.class, com.gossip.protobuf.MessageProtos.Clock.Builder.class);
    }

    public static com.google.protobuf.Parser<Clock> PARSER =
        new com.google.protobuf.AbstractParser<Clock>() {
      public Clock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Clock(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Clock> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PROCESS_FIELD_NUMBER = 1;
    private int process_;
    /**
     * <code>optional int32 Process = 1;</code>
     */
    public boolean hasProcess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 Process = 1;</code>
     */
    public int getProcess() {
      return process_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>optional int32 Count = 2;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 Count = 2;</code>
     */
    public int getCount() {
      return count_;
    }

    private void initFields() {
      process_ = 0;
      count_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, process_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, count_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, process_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gossip.protobuf.MessageProtos.Clock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gossip.protobuf.MessageProtos.Clock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gossip.protobuf.MessageProtos.Clock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gossip.protobuf.MessageProtos.Clock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gossip.protobuf.MessageProtos.Clock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gossip.protobuf.MessageProtos.Clock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gossip.protobuf.MessageProtos.Clock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gossip.protobuf.MessageProtos.Clock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gossip.protobuf.MessageProtos.Clock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gossip.protobuf.MessageProtos.Clock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gossip.protobuf.MessageProtos.Clock prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Clock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Clock)
        com.gossip.protobuf.MessageProtos.ClockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gossip.protobuf.MessageProtos.internal_static_Clock_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gossip.protobuf.MessageProtos.internal_static_Clock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gossip.protobuf.MessageProtos.Clock.class, com.gossip.protobuf.MessageProtos.Clock.Builder.class);
      }

      // Construct using com.gossip.protobuf.MessageProtos.Clock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        process_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gossip.protobuf.MessageProtos.internal_static_Clock_descriptor;
      }

      public com.gossip.protobuf.MessageProtos.Clock getDefaultInstanceForType() {
        return com.gossip.protobuf.MessageProtos.Clock.getDefaultInstance();
      }

      public com.gossip.protobuf.MessageProtos.Clock build() {
        com.gossip.protobuf.MessageProtos.Clock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gossip.protobuf.MessageProtos.Clock buildPartial() {
        com.gossip.protobuf.MessageProtos.Clock result = new com.gossip.protobuf.MessageProtos.Clock(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.process_ = process_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gossip.protobuf.MessageProtos.Clock) {
          return mergeFrom((com.gossip.protobuf.MessageProtos.Clock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gossip.protobuf.MessageProtos.Clock other) {
        if (other == com.gossip.protobuf.MessageProtos.Clock.getDefaultInstance()) return this;
        if (other.hasProcess()) {
          setProcess(other.getProcess());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gossip.protobuf.MessageProtos.Clock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gossip.protobuf.MessageProtos.Clock) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int process_ ;
      /**
       * <code>optional int32 Process = 1;</code>
       */
      public boolean hasProcess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 Process = 1;</code>
       */
      public int getProcess() {
        return process_;
      }
      /**
       * <code>optional int32 Process = 1;</code>
       */
      public Builder setProcess(int value) {
        bitField0_ |= 0x00000001;
        process_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Process = 1;</code>
       */
      public Builder clearProcess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        process_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>optional int32 Count = 2;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 Count = 2;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 Count = 2;</code>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Count = 2;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Clock)
    }

    static {
      defaultInstance = new Clock(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Clock)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hearGossipRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hearGossipRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Clock_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Clock_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"5\n\021hearGossipRequest\022\013\n\003" +
      "msg\030\001 \001(\t\022\023\n\003clk\030\002 \001(\0132\006.Clock\"\'\n\005Clock\022" +
      "\017\n\007Process\030\001 \001(\005\022\r\n\005Count\030\002 \001(\005B$\n\023com.g" +
      "ossip.protobufB\rMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hearGossipRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hearGossipRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hearGossipRequest_descriptor,
        new java.lang.String[] { "Msg", "Clk", });
    internal_static_Clock_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Clock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Clock_descriptor,
        new java.lang.String[] { "Process", "Count", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
